import type { Locale } from "./i18n";
import { DEFAULT_SOURCE_URL } from "./admin-helpers";
import type {
  AdminCategoryScope,
  BackupCounts,
  BackupRestoreResponse,
  FactoryResetResponse,
  ToolImportResponse
} from "./types";

export function getAdminMaintenanceText(locale: Locale) {
  if (locale === "zh") {
    const siteText = {
      siteTitle: "基本信息",
      siteDescription: "\u4fee\u6539\u524d\u53f0\u548c\u540e\u53f0\u663e\u793a\u7684\u7f51\u7ad9\u540d\u79f0\u4e0e\u56fe\u6807\u3002\u4e0d\u586b\u5199\u5219\u4f7f\u7528\u9ed8\u8ba4\u7ad9\u70b9\u4fe1\u606f\u3002",
      siteNameLabel: "\u7f51\u7ad9\u540d\u79f0",
      siteSubtitleLabel: "\u7f51\u7ad9\u526f\u6807\u9898",
      siteIconLabel: "\u7f51\u7ad9\u56fe\u6807 URL",
      siteIconChoiceHelp:
        "\u53ef\u586b\u5199\u56fe\u6807\u94fe\u63a5\u6216\u4e0a\u4f20\u672c\u5730\u56fe\u7247\uff0c\u652f\u6301 PNG\u3001WEBP\u3001JPG\u3001GIF\u3001ICO\uff0c\u6700\u5927 1MB\u3002",
      siteIconPlaceholder: "https://example.com/icon.png",
      siteIconUpload: "选择图片",
      siteIconUploaded: "\u5df2\u4f7f\u7528\u672c\u5730\u4e0a\u4f20\u56fe\u6807",
      siteIconUploadInvalid: "\u8bf7\u9009\u62e9\u652f\u6301\u7684\u56fe\u7247\u683c\u5f0f\u3002",
      siteIconUploadTooLarge: "\u56fe\u7247\u8bf7\u63a7\u5236\u5728 1MB \u4ee5\u5185\u3002",
      siteSave: "保存信息",
      siteUpdated: "\u7ad9\u70b9\u4fe1\u606f\u5df2\u66f4\u65b0\u3002",
      siteReset: "\u6062\u590d\u9ed8\u8ba4",
      siteResetDone: "\u7ad9\u70b9\u4fe1\u606f\u5df2\u6062\u590d\u9ed8\u8ba4\u3002",
      siteIconInvalid: "\u7f51\u7ad9\u56fe\u6807\u5fc5\u987b\u662f\u6709\u6548\u7684 http/https \u5730\u5740\uff0c\u6216\u652f\u6301\u7684\u56fe\u7247\u6587\u4ef6\u3002",
      aboutSettingsTitle: "\u5173\u4e8e\u9875\u9762",
      aboutSettingsDescription: "\u5206\u522b\u7f16\u5199\u4e2d\u82f1\u6587\u5173\u4e8e\u9875\u9762\uff0c\u524d\u53f0\u4f1a\u6309\u5f53\u524d\u8bed\u8a00\u663e\u793a\u3002",
      aboutSave: "保存关于",
      aboutReset: "\u6062\u590d\u9ed8\u8ba4",
      aboutResetDone: "\u5173\u4e8e\u9875\u5df2\u6062\u590d\u9ed8\u8ba4\u3002",
      aboutUpdated: "\u5173\u4e8e\u9875\u9762\u5df2\u66f4\u65b0\u3002",
      privacySettingsTitle: "\u9690\u79c1\u653f\u7b56",
      privacySettingsDescription: "\u5206\u522b\u7f16\u5199\u4e2d\u82f1\u6587\u9690\u79c1\u653f\u7b56\uff0c\u524d\u53f0\u4f1a\u6309\u5f53\u524d\u8bed\u8a00\u663e\u793a\u3002",
      privacySave: "\u4fdd\u5b58\u9690\u79c1",
      privacyResetDone: "\u9690\u79c1\u653f\u7b56\u5df2\u6062\u590d\u9ed8\u8ba4\u3002",
      privacyUpdated: "\u9690\u79c1\u653f\u7b56\u5df2\u66f4\u65b0\u3002",
      termsSettingsTitle: "\u670d\u52a1\u6761\u6b3e",
      termsSettingsDescription: "\u5206\u522b\u7f16\u5199\u4e2d\u82f1\u6587\u670d\u52a1\u6761\u6b3e\uff0c\u524d\u53f0\u4f1a\u6309\u5f53\u524d\u8bed\u8a00\u663e\u793a\u3002",
      termsSave: "\u4fdd\u5b58\u6761\u6b3e",
      termsResetDone: "\u670d\u52a1\u6761\u6b3e\u5df2\u6062\u590d\u9ed8\u8ba4\u3002",
      termsUpdated: "\u670d\u52a1\u6761\u6b3e\u5df2\u66f4\u65b0\u3002",
      legalChinese: "\u4e2d\u6587 Markdown",
      legalEnglish: "\u82f1\u6587 Markdown",
      footerTitle: "\u9875\u811a\u8bbe\u7f6e",
      footerDescription: "\u81ea\u5b9a\u4e49\u524d\u53f0\u5e95\u90e8\u7684\u4ecb\u7ecd\u3001\u8d5e\u52a9\u6309\u94ae\u548c\u94fe\u63a5\u680f\u76ee\u3002\u4e0d\u586b\u5199\u5219\u4f7f\u7528\u9ed8\u8ba4\u9875\u811a\u914d\u7f6e\u3002",
      footerIntroLabel: "\u9875\u811a\u4ecb\u7ecd",
      footerSponsorLabel: "\u8d5e\u52a9\u6309\u94ae\u6587\u5b57",
      footerSponsorUrl: "\u8d5e\u52a9\u6309\u94ae\u94fe\u63a5",
      footerSocialLinks: "\u793e\u4ea4\u56fe\u6807\u94fe\u63a5 JSON",
      footerGroups: "\u9875\u811a\u680f\u76ee JSON",
      footerJsonHelp: "\u793e\u4ea4\u94fe\u63a5\u4f7f\u7528 [{\"label\":\"GitHub\",\"href\":\"https://...\"}]\uff1b\u680f\u76ee\u4f7f\u7528 [{\"title\":\"\u4ea7\u54c1\",\"links\":[{\"label\":\"\u5de5\u5177\",\"href\":\"/tools\"}]}]\u3002",
      footerSave: "保存页脚",
      footerReset: "\u6062\u590d\u9ed8\u8ba4",
      footerResetDone: "\u9875\u811a\u8bbe\u7f6e\u5df2\u6062\u590d\u9ed8\u8ba4\u3002",
      footerUpdated: "\u9875\u811a\u8bbe\u7f6e\u5df2\u66f4\u65b0\u3002",
      footerJsonInvalid: "\u9875\u811a JSON \u683c\u5f0f\u4e0d\u6b63\u786e\u3002",
      footerSocialJsonInvalid: "\u793e\u4ea4\u94fe\u63a5 JSON \u5fc5\u987b\u5305\u542b label \u548c href \u5b57\u6bb5\u3002",
      footerGroupsJsonInvalid: "\u9875\u811a\u680f\u76ee JSON \u5fc5\u987b\u5305\u542b title \u548c links \u5b57\u6bb5\u3002",
      homeSettingsTitle: "\u9996\u9875\u6587\u6848",
      homeSettingsDescription:
        "\u5206\u522b\u8bbe\u7f6e\u4e2d\u6587\u548c\u82f1\u6587\u9996\u9875\u9996\u5c4f\u6587\u6848\uff0c\u7559\u7a7a\u65f6\u4f7f\u7528\u5bf9\u5e94\u8bed\u8a00\u7684\u9ed8\u8ba4\u6587\u6848\u3002",
      homeChinese: "\u4e2d\u6587\u6587\u6848",
      homeEnglish: "\u82f1\u6587\u6587\u6848",
      homeTitleTop: "\u6807\u9898\u7b2c\u4e00\u884c",
      homeTitleBottom: "\u6807\u9898\u7b2c\u4e8c\u884c",
      homeDescription: "\u9996\u9875\u7b80\u4ecb",
      homeSave: "\u4fdd\u5b58\u6587\u6848",
      homeReset: "\u6062\u590d\u9ed8\u8ba4",
      homeResetDone: "\u9996\u9875\u6587\u6848\u5df2\u6062\u590d\u9ed8\u8ba4\u3002",
      homeUpdated: "\u9996\u9875\u6587\u6848\u5df2\u66f4\u65b0\u3002",
    };

    return {
      ...siteText,
      importExportTab: "导入导出",
      linkCheckTab: "链接检测",
      sourceTitle: "导入",
      sourceDescription: "\u4ece\u517c\u5bb9\u7684 JSON \u8ba2\u9605\u6e90\u8bfb\u53d6\u5de5\u5177\u6570\u636e\u3002\u9ed8\u8ba4\u5730\u5740\u6307\u5411 HTools \u4e3b\u4ed3\u5e93\u7684\u5728\u7ebf\u6570\u636e\u6e90\uff0c\u4e5f\u53ef\u4ee5\u586b\u5199\u5176\u4ed6\u516c\u5f00\u6e90\uff0c\u4f8b\u5982\u5176\u4ed6\u7ad9\u70b9\u516c\u5f00\u7684 /api/htools.json\u3002\u68c0\u6d4b\u53ea\u6821\u9a8c\u683c\u5f0f\u548c\u6570\u91cf\uff0c\u5bfc\u5165\u624d\u4f1a\u5199\u5165 D1\u3002",
      sourceUrl: "\u8ba2\u9605\u6e90 URL",
      sourcePlaceholder: DEFAULT_SOURCE_URL,
      sourceDetect: "\u68c0\u6d4b\u8ba2\u9605",
      sourceImport: "\u5bfc\u5165\u8ba2\u9605",
      sourceExport: "\u5bfc\u51fa\u8ba2\u9605",
      sourceExportTitle: "导出",
      sourceExportDescription: "将当前工具库导出为兼容的 htools.json 订阅源文件。",
      sourceExportCount: "工具数量",
      sourceExportFormat: "文件格式",
      sourceExportScope: "数据范围",
      sourceExportScopeAll: "全部工具",
      sourceMode: "\u5bfc\u5165\u65b9\u5f0f",
      sourceModeSkip: "\u8df3\u8fc7\u91cd\u590d",
      sourceModeUpsert: "\u8986\u76d6\u66f4\u65b0",
      sourceModeHelp: "\u9ed8\u8ba4\u8df3\u8fc7\u5df2\u5b58\u5728 URL\uff1b\u9700\u8981\u540c\u6b65\u66f4\u65b0\u65f6\u518d\u9009\u62e9\u8986\u76d6\u3002",
      sourceEmpty: "\u8ba2\u9605\u6e90\u6ca1\u6709\u53ef\u8bfb\u53d6\u7684\u5de5\u5177\u6570\u636e\u3002",
      sourceInvalid: "JSON \u5fc5\u987b\u662f\u6570\u7ec4\uff0c\u6216\u5305\u542b tools \u6570\u7ec4\u7684\u5bf9\u8c61\u3002",
      sourceTotal: "\u603b\u6570",
      sourceValid: "\u6709\u6548",
      sourceDuplicate: "\u8ba2\u9605\u6e90\u5185\u91cd\u590d",
      sourceExisting: "\u672c\u7ad9\u91cd\u590d",
      sourceMissing: "\u7f3a\u5b57\u6bb5",
      sourceWillCreate: "\u5c06\u65b0\u589e",
      sourceWillUpdate: "\u5c06\u66f4\u65b0",
      sourceWillSkip: "\u5c06\u8df3\u8fc7",
      sourceErrors: "\u683c\u5f0f\u95ee\u9898",
      sourceItemObject: "\u8be5\u6761\u76ee\u5fc5\u987b\u662f\u5bf9\u8c61\u3002",
      sourceUrlInvalid: "url \u5fc5\u987b\u662f\u6709\u6548\u7f51\u5740\u3002",
      sourceDemoUrlInvalid: "demoUrl \u5fc5\u987b\u662f\u6709\u6548\u7f51\u5740\u3002",
      sourceImageInvalid: "image \u5fc5\u987b\u662f\u6709\u6548\u7f51\u5740\u3002",
      sourceOperationFailed: "\u8ba2\u9605\u6e90\u64cd\u4f5c\u5931\u8d25\uff0c\u8bf7\u68c0\u67e5\u5730\u5740\u6216\u7a0d\u540e\u91cd\u8bd5\u3002",
      systemTitle: "\u7cfb\u7edf\u8bbe\u7f6e",
      systemDescription: "\u7ba1\u7406\u7ad9\u70b9\u7ea7\u5f00\u5173\u548c\u516c\u5f00\u80fd\u529b\u3002",
      systemGroupGeneral: "站点信息",
      systemGroupIntegrations: "服务设置",
      systemGroupSecurity: "管理设置",
      unsavedTitle: "\u672a\u4fdd\u5b58\u8bbe\u7f6e",
      unsavedDescription:
        "\u5f53\u524d\u8bbe\u7f6e\u6709\u672a\u4fdd\u5b58\u66f4\u6539\uff0c\u79bb\u5f00\u540e\u5c06\u4e22\u5931\u3002",
      unsavedStay: "\u7ee7\u7eed\u7f16\u8f91",
      unsavedLeave: "\u653e\u5f03\u66f4\u6539",
      systemRetry: "重新加载",
      githubSubmissionTitle: "GitHub \u63d0\u4ea4\u8bbe\u7f6e",
      githubSubmissionDescription: "\u914d\u7f6e\u63a5\u6536\u516c\u5f00\u5de5\u5177\u5efa\u8bae\u7684 GitHub \u4ed3\u5e93\uff0c\u7528\u6237\u5c06\u524d\u5f80 GitHub \u786e\u8ba4\u5e76\u521b\u5efa Issue\u3002",
      securityTitle: "\u7ba1\u7406\u5458\u5b89\u5168\u8bbe\u7f6e",
      securityDescription: "\u7edf\u4e00\u7ba1\u7406\u540e\u53f0\u767b\u5f55\u5bc6\u7801\uff0c\u5efa\u8bae\u5b9a\u671f\u66f4\u65b0\u5e76\u907f\u514d\u4f7f\u7528\u5f31\u5bc6\u7801\u3002",
      securityCurrent: "\u5f53\u524d\u5bc6\u7801",
      securityNew: "\u65b0\u5bc6\u7801",
      securityConfirm: "\u786e\u8ba4\u65b0\u5bc6\u7801",
      securitySave: "\u66f4\u65b0\u5bc6\u7801",
      securityConfigured: "\u5df2\u8bbe\u7f6e D1 \u5bc6\u7801",
      securityUsingEnv: "\u6b63\u5728\u4f7f\u7528\u73af\u5883\u53d8\u91cf\u5bc6\u7801",
      securityCurrentRequired: "\u8bf7\u8f93\u5165\u5f53\u524d\u5bc6\u7801\u3002",
      securityNewRequired: "\u8bf7\u8f93\u5165\u65b0\u5bc6\u7801\u3002",
      securityConfirmRequired: "\u8bf7\u786e\u8ba4\u65b0\u5bc6\u7801\u3002",
      securityMismatch: "\u4e24\u6b21\u8f93\u5165\u7684\u65b0\u5bc6\u7801\u4e0d\u4e00\u81f4\u3002",
      securityCurrentIncorrect: "\u5f53\u524d\u5bc6\u7801\u4e0d\u6b63\u786e\u3002",
      securityUnchanged: "\u65b0\u5bc6\u7801\u4e0d\u80fd\u4e0e\u5f53\u524d\u5bc6\u7801\u76f8\u540c\u3002",
      securityUpdated: "\u7ba1\u7406\u5458\u5bc6\u7801\u5df2\u66f4\u65b0\u3002",
      backupTitle: "\u5907\u4efd\u4e0e\u6062\u590d",
      backupDescription: "\u5728\u53d8\u66f4\u524d\u5bfc\u51fa\u5f53\u524d\u6570\u636e\uff0c\u5fc5\u8981\u65f6\u518d\u5bfc\u5165\u6062\u590d\uff0c\u51cf\u5c11\u8bef\u64cd\u4f5c\u98ce\u9669\u3002",
      backupHelp:
        "完整备份包含工具库、文章、内容流、分类和站点设置；不会导出管理员密码或管理员登录会话。恢复会覆盖当前站点内容，建议先导出备份。",
      backupExport: "\u5bfc\u51fa\u5907\u4efd",
      backupChoose: "选择文件",
      backupRestore: "\u6062\u590d\u5907\u4efd",
      backupEmpty: "\u8bf7\u5148\u9009\u62e9\u5907\u4efd JSON \u6587\u4ef6\u3002",
      backupInvalid: "请选择 HTools 完整备份 JSON 文件。",
      backupTooLarge: "备份文件请控制在 10MB 以内。",
      backupRestoreConfirm: (counts: BackupCounts) =>
        `确定恢复此备份吗？将用 ${counts.tools} 个工具、${counts.articles} 篇文章、${counts.contentSources} 个内容源和 ${counts.contentItems} 条内容覆盖当前站点。`,
      publicTitle: "我的订阅源",
      publicDescription: "默认关闭。开启后，其他人可以通过下方地址订阅当前工具列表。",
      publicEnabled: "\u5df2\u5f00\u542f",
      publicDisabled: "\u5df2\u5173\u95ed",
      publicSourceUrlLabel: "当前订阅源地址",
      publicEnable: "开启订阅",
      publicDisable: "关闭订阅",
      publicUpdated: "订阅源设置已更新。",
      publicEnabledMessage: "订阅源已开启。",
      publicDisabledMessage: "订阅源已关闭。",
      turnstileTitle: "Cloudflare Turnstile",
      turnstileDescription: "用于保护管理员登录并减少恶意尝试；请在项目配置下方两个环境变量，即可开启或关闭，密钥不会在后台显示。",
      turnstileSiteKeyLabel: "Cloudflare 站点密钥（Site Key）",
      turnstileSecretKeyLabel: "Cloudflare 密钥（Secret Key）",
      turnstileAvailable: "已配置",
      turnstileUnavailable: "未配置",
      turnstileEnabled: "已开启",
      turnstileDisabled: "已关闭",
      turnstileEnable: "开启验证",
      turnstileDisable: "关闭验证",
      turnstileNotConfigured: "尚未完整配置 Turnstile 环境变量，当前无法开启此功能。",
      turnstileEnabledMessage: "登录验证已开启。",
      turnstileDisabledMessage: "登录验证已关闭。",
      umamiTitle: "Umami 访问统计",
      umamiDescription: "连接自托管 Umami 或 Umami Cloud，统计站点访问情况；保存完整配置后可在这里开启或关闭。",
      umamiScriptUrlLabel: "统计脚本地址",
      umamiScriptUrlPlaceholder: "https://example.com/script.js",
      umamiWebsiteIdLabel: "Website ID",
      umamiWebsiteIdPlaceholder: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      umamiEnabled: "已开启",
      umamiDisabled: "已关闭",
      umamiEnable: "开启统计",
      umamiDisable: "关闭统计",
      umamiSave: "保存设置",
      umamiUpdated: "Umami 设置已保存。",
      umamiEnabledMessage: "Umami 访问统计已开启。",
      umamiDisabledMessage: "Umami 访问统计已关闭。",
      umamiRequired: "请先填写并保存统计脚本地址和 Website ID。",
      umamiInvalidUrl: "请输入有效的 Umami 统计脚本地址。",
      proxyTitle: "代理访问",
      proxyDescription: "为无法直连的外部图片或链接提供代理转发，仅代理下方所选范围；站内页面、API 与站点图标仍保持直连。\n\n提示：请谨慎开启。部分站点、图片防盗链或登录跳转可能与代理不兼容，如果开启后页面显示异常，请先关闭代理或更换代理服务。",
      proxyHelp: "全站代理会代理外部链接和外部图片；仅代理图片只代理工具预览图、文章图片、内容流封面等图片资源，普通外部链接保持直连。直接拼接使用“代理地址 + 目标地址”；Edgeone-Proxy 标准使用 `/proxy?url=`；Edgeone-Proxy 高级使用 `/advanced-proxy?url=`。\n\nHTools 不内置代理服务，如需使用，可自行部署代理项目后填写部署地址。",
      proxyEnabled: "\u5df2\u5f00\u542f",
      proxyDisabled: "\u5df2\u5173\u95ed",
      proxyUrlLabel: "\u4ee3\u7406\u670d\u52a1\u5730\u5740",
      proxyPlaceholder: "https://your-proxy.example.com/",
      proxyScopeLabel: "代理范围",
      proxyScopeAll: "全站代理",
      proxyScopeImages: "仅代理图片",
      proxyModeLabel: "\u4ee3\u7406\u8bbf\u95ee\u89c4\u5219",
      proxyModePrefix: "\u76f4\u63a5\u62fc\u63a5",
      proxyModeEdgeOneProxy: "Edgeone-Proxy \u6807\u51c6",
      proxyModeEdgeOneAdvanced: "Edgeone-Proxy \u9ad8\u7ea7",
      proxyProjectLink: "Edgeone-Proxy \u9879\u76ee",
      proxyEnable: "\u5f00\u542f\u4ee3\u7406",
      proxyDisable: "\u5173\u95ed\u4ee3\u7406",
      proxySave: "保存设置",
      proxyRequired: "\u5f00\u542f\u4ee3\u7406\u524d\u8bf7\u586b\u5199\u4ee3\u7406\u670d\u52a1\u5730\u5740\u3002",
      proxyInvalid: "\u4ee3\u7406\u670d\u52a1\u5730\u5740\u5fc5\u987b\u662f\u6709\u6548\u7684 http/https \u5730\u5740\u3002",
      proxyUpdated: "\u4ee3\u7406\u8bbe\u7f6e\u5df2\u66f4\u65b0\u3002",
      resetTitle: "\u6062\u590d\u9ed8\u8ba4\u8bbe\u7f6e",
      resetDescription:
        "\u6e05\u7a7a\u5f53\u524d\u5de5\u5177\u3001\u6587\u7ae0\u3001\u5185\u5bb9\u6d41\u548c\u9884\u5efa\u5206\u7c7b\uff0c\u5e76\u5173\u95ed\u7ad9\u70b9\u6e90\u3002\u7ba1\u7406\u5458\u5bc6\u7801\u548c GitHub \u63d0\u4ea4\u8bbe\u7f6e\u4e0d\u4f1a\u88ab\u6e05\u9664\u3002",
      resetWarning:
        "\u6b64\u64cd\u4f5c\u5c06\u5220\u9664\u6240\u6709\u5bfc\u5165\u6570\u636e\uff0c\u5efa\u8bae\u5148\u5bfc\u51fa\u5b8c\u6574\u5907\u4efd\u3002",
      resetButton: "恢复默认",
      resetConfirm:
        "\u786e\u5b9a\u8981\u6062\u590d\u9ed8\u8ba4\u8bbe\u7f6e\u5417\uff1f\u8fd9\u5c06\u5220\u9664\u5de5\u5177\u3001\u6587\u7ae0\u3001\u5185\u5bb9\u6d41\u548c\u9884\u5efa\u5206\u7c7b\uff0c\u5e76\u5173\u95ed\u7ad9\u70b9\u6e90\u3002",
      linkModuleTitle: "\u672c\u7ad9\u94fe\u63a5\u68c0\u6d4b",
      linkModuleDescription: "\u68c0\u6d4b\u5df2\u4fdd\u5b58\u5de5\u5177\u7684\u9879\u76ee\u5730\u5740\u548c\u6f14\u793a\u7ad9\u70b9\u662f\u5426\u53ef\u8bbf\u95ee\uff0c\u7ed3\u679c\u53ea\u5c55\u793a\uff0c\u4e0d\u4f1a\u4fee\u6539\u94fe\u63a5\u3002",
      urlLabel: "\u9879\u76ee\u5730\u5740",
      demoUrlLabel: "\u6f14\u793a\u7ad9\u70b9",
      sourceChecked: (count: number) => `\u8ba2\u9605\u6e90\u68c0\u6d4b\u5b8c\u6210\uff1a\u5171 ${count} \u6761\u3002`,
      sourceImportSummary: (result: ToolImportResponse) =>
        `\u5bfc\u5165\u5b8c\u6210\uff1a\u65b0\u589e ${result.imported}\uff0c\u66f4\u65b0 ${result.updated}\uff0c\u8df3\u8fc7 ${result.skipped}\uff0c\u5931\u8d25 ${result.failed}\u3002`,
      sourceExported: (count: number) => `导出完成：共 ${count} 个工具，文件已下载。`,
      sourceErrorItem: (index: number, message: string) =>
        `\u7b2c ${index + 1} \u6761\uff1a${message}`,
      sourceRequestFailed: (status: number) => `\u8ba2\u9605\u6e90\u8bf7\u6c42\u5931\u8d25\uff1a${status}`,
      sourceRequired: (fields: string) => `${fields} \u4e3a\u5fc5\u586b\u5b57\u6bb5\u3002`,
      securityUpdatedAt: (date: string) => `\u4e0a\u6b21\u66f4\u65b0\uff1a${date}`,
      backupExported: (counts: BackupCounts) =>
        `已导出完整备份：工具 ${counts.tools}，文章 ${counts.articles}，内容源 ${counts.contentSources}，内容 ${counts.contentItems}。`,
      backupReady: (name: string, counts: BackupCounts) =>
        `已读取 ${name}：工具 ${counts.tools}，文章 ${counts.articles}，内容源 ${counts.contentSources}，内容 ${counts.contentItems}。`,
      backupRestoreSummary: (result: BackupRestoreResponse) =>
        `恢复完成：工具 ${result.counts.tools}，文章 ${result.counts.articles}，内容源 ${result.counts.contentSources}，内容 ${result.counts.contentItems}。`,
      resetDone: (result: FactoryResetResponse) =>
        `\u5df2\u6062\u590d\u9ed8\u8ba4\u8bbe\u7f6e\uff1a\u5220\u9664\u5de5\u5177 ${result.counts.tools}\uff0c\u6587\u7ae0 ${result.counts.articles}\uff0c\u5185\u5bb9\u6e90 ${result.counts.contentSources}\uff0c\u5185\u5bb9 ${result.counts.contentItems}\u3002`
    };
  }

  return {
    importExportTab: "Import / Export",
    linkCheckTab: "Link Check",
    sourceTitle: "Import",
    sourceDescription:
      "Read tool data from a compatible JSON subscription source. The default URL points to the online source in the HTools main repository; you can also use other public sources, such as another site's /api/htools.json. Check only validates the source; import writes to D1.",
    sourceUrl: "Subscription source URL",
    sourcePlaceholder: DEFAULT_SOURCE_URL,
    sourceDetect: "Check Subscription",
    sourceImport: "Import Subscription",
    sourceExport: "Export Subscription",
    sourceExportTitle: "Export",
    sourceExportDescription:
      "Export the current tool library as a compatible htools.json subscription source file.",
    sourceExportCount: "Tool count",
    sourceExportFormat: "File format",
    sourceExportScope: "Data scope",
    sourceExportScopeAll: "All tools",
    sourceMode: "Import mode",
    sourceModeSkip: "Skip duplicates",
    sourceModeUpsert: "Overwrite same URL",
    sourceModeHelp:
      "Duplicate URLs are skipped by default; choose overwrite when you want to sync updates.",
    sourceEmpty: "The source did not include readable tool data.",
    sourceInvalid: "JSON must be an array or an object with a tools array.",
    sourceChecked: (count: number) => `Subscription check complete: ${count} items.`,
    sourceImportSummary: (result: ToolImportResponse) =>
      `Import complete: ${result.imported} created, ${result.updated} updated, ${result.skipped} skipped, ${result.failed} failed.`,
    sourceExported: (count: number) =>
      `Export complete: ${count} ${count === 1 ? "tool" : "tools"}; the file has been downloaded.`,
    sourceTotal: "Total",
    sourceValid: "Valid",
    sourceDuplicate: "Subscription dupes",
    sourceExisting: "Existing",
    sourceMissing: "Missing",
    sourceWillCreate: "Will create",
    sourceWillUpdate: "Will update",
    sourceWillSkip: "Will skip",
    sourceErrors: "Format issues",
    sourceErrorItem: (index: number, message: string) =>
      `Item ${index + 1}: ${message}`,
    sourceRequestFailed: (status: number) => `Source request failed: ${status}`,
    sourceItemObject: "Item must be an object.",
    sourceRequired: (fields: string) => `${fields} is required.`,
    sourceUrlInvalid: "url must be a valid URL.",
    sourceDemoUrlInvalid: "demoUrl must be a valid URL.",
    sourceImageInvalid: "image must be a valid URL.",
    sourceOperationFailed:
      "Subscription source operation failed. Check the URL or try again later.",
    systemTitle: "System Settings",
    systemDescription: "Manage site-level switches and public capabilities.",
    systemGroupGeneral: "Site Information",
    systemGroupIntegrations: "Service Settings",
    systemGroupSecurity: "Management Settings",
    unsavedTitle: "Unsaved Settings",
    unsavedDescription:
      "You have unsaved settings changes. Leaving this section will discard them.",
    unsavedStay: "Keep Editing",
    unsavedLeave: "Discard Changes",
    systemRetry: "Reload",
    siteTitle: "Basic Information",
    siteDescription:
      "Change the site name and icon shown in the frontend and admin area. Leave blank to use the default site identity.",
    siteNameLabel: "Site name",
    siteSubtitleLabel: "Site subtitle",
    siteIconLabel: "Site icon URL",
    siteIconChoiceHelp:
      "Enter an icon URL or upload a PNG, WEBP, JPG, GIF, or ICO image up to 1MB.",
    siteIconPlaceholder: "https://example.com/icon.png",
    siteIconUpload: "Choose Image",
    siteIconUploaded: "Using uploaded local icon",
    siteIconUploadInvalid: "Choose a supported image format.",
    siteIconUploadTooLarge: "Keep the image under 1MB.",
    siteSave: "Save Info",
    siteUpdated: "Site identity updated.",
    siteReset: "Restore Defaults",
    siteResetDone: "Site identity restored to defaults.",
    siteIconInvalid:
      "Site icon must be a valid http/https URL or a supported image file.",
    aboutSettingsTitle: "About Page",
    aboutSettingsDescription:
      "Edit the Chinese and English About pages shown for each frontend language.",
    aboutSave: "Save About",
    aboutReset: "Restore Defaults",
    aboutResetDone: "About page restored to defaults.",
    aboutUpdated: "About page updated.",
    privacySettingsTitle: "Privacy Policy",
    privacySettingsDescription:
      "Edit the Chinese and English privacy policies shown for each frontend language.",
    privacySave: "Save Privacy",
    privacyResetDone: "Privacy policy restored to defaults.",
    privacyUpdated: "Privacy policy updated.",
    termsSettingsTitle: "Terms of Service",
    termsSettingsDescription:
      "Edit the Chinese and English terms shown for each frontend language.",
    termsSave: "Save Terms",
    termsResetDone: "Terms of service restored to defaults.",
    termsUpdated: "Terms of service updated.",
    legalChinese: "Chinese Markdown",
    legalEnglish: "English Markdown",
    footerTitle: "Footer Settings",
    footerDescription:
      "Customize the frontend footer description, sponsor button, and link columns. Leave blank to use the default footer settings.",
    footerIntroLabel: "Footer description",
    footerSponsorLabel: "Sponsor button text",
    footerSponsorUrl: "Sponsor button URL",
    footerSocialLinks: "Social icon links JSON",
    footerGroups: "Footer columns JSON",
    footerJsonHelp:
      'Social links use [{"label":"GitHub","href":"https://..."}]; columns use [{"title":"Product","links":[{"label":"Tools","href":"/tools"}]}].',
    footerSave: "Save Footer",
    footerReset: "Restore Defaults",
    footerResetDone: "Footer settings restored to defaults.",
    footerUpdated: "Footer settings updated.",
    footerJsonInvalid: "Footer JSON is not valid.",
    footerSocialJsonInvalid: "Social links JSON must contain label and href fields.",
    footerGroupsJsonInvalid: "Footer columns JSON must contain title and links fields.",
    homeSettingsTitle: "Homepage Copy",
    homeSettingsDescription:
      "Set the Chinese and English homepage hero copy separately. Leave fields blank to use the language defaults.",
    homeChinese: "Chinese Copy",
    homeEnglish: "English Copy",
    homeTitleTop: "First headline line",
    homeTitleBottom: "Second headline line",
    homeDescription: "Homepage description",
    homeSave: "Save Copy",
    homeReset: "Restore Defaults",
    homeResetDone: "Homepage copy restored.",
    homeUpdated: "Homepage copy updated.",
    githubSubmissionTitle: "GitHub Submission Settings",
    githubSubmissionDescription:
      "Configure the GitHub repository that receives public tool suggestions. Users continue to GitHub to review and create the issue.",
    securityTitle: "Admin Security Settings",
    securityDescription:
      "Manage the admin login password in one place. Update it regularly and avoid weak passwords.",
    securityCurrent: "Current password",
    securityNew: "New password",
    securityConfirm: "Confirm new password",
    securitySave: "Update Password",
    securityConfigured: "D1 password configured",
    securityUsingEnv: "Using environment password",
    securityUpdatedAt: (date: string) => `Last updated: ${date}`,
    securityCurrentRequired: "Current password is required.",
    securityNewRequired: "New password is required.",
    securityConfirmRequired: "Confirm the new password.",
    securityMismatch: "The new passwords do not match.",
    securityCurrentIncorrect: "Current password is incorrect.",
    securityUnchanged: "The new password must be different from the current password.",
    securityUpdated: "Admin password updated.",
    backupTitle: "Backup and Restore",
    backupDescription:
      "Export the current data before changes, then import it back if needed to reduce accidental-operation risk.",
    backupHelp:
      "A full backup includes tools, articles, content flows, categories, and site settings. Admin passwords and administrator login sessions are not exported. Restore overwrites the current site content.",
    backupExport: "Export Backup",
    backupChoose: "Choose File",
    backupRestore: "Restore Backup",
    backupEmpty: "Choose a backup JSON file first.",
    backupInvalid: "Choose an HTools full backup JSON file.",
    backupTooLarge: "Keep the backup file under 10MB.",
    backupRestoreConfirm: (counts: BackupCounts) =>
      `Restore this backup? It will replace the current site with ${counts.tools} tools, ${counts.articles} articles, ${counts.contentSources} sources, and ${counts.contentItems} items.`,
    backupExported: (counts: BackupCounts) =>
      `Exported full backup: ${counts.tools} tools, ${counts.articles} articles, ${counts.contentSources} sources, ${counts.contentItems} items.`,
    backupReady: (name: string, counts: BackupCounts) =>
      `Loaded ${name}: ${counts.tools} tools, ${counts.articles} articles, ${counts.contentSources} sources, ${counts.contentItems} items.`,
    backupRestoreSummary: (result: BackupRestoreResponse) =>
      `Restore complete: ${result.counts.tools} tools, ${result.counts.articles} articles, ${result.counts.contentSources} sources, ${result.counts.contentItems} items.`,
    publicTitle: "My Subscription Feed",
    publicDescription:
      "Off by default. Once enabled, others can subscribe to the current tool list from the address below.",
    publicEnabled: "Enabled",
    publicDisabled: "Disabled",
    publicSourceUrlLabel: "Current subscription feed URL",
    publicEnable: "Enable Feed",
    publicDisable: "Disable Feed",
    publicUpdated: "Subscription feed setting updated.",
    publicEnabledMessage: "Subscription feed enabled.",
    publicDisabledMessage: "Subscription feed disabled.",
    turnstileTitle: "Cloudflare Turnstile",
    turnstileDescription: "Protects admin login while reducing malicious attempts. Configure both variables below in the project to enable or disable it; secrets are never shown in the admin interface.",
    turnstileSiteKeyLabel: "Cloudflare Site Key",
    turnstileSecretKeyLabel: "Cloudflare Secret Key",
    turnstileAvailable: "Configured",
    turnstileUnavailable: "Not configured",
    turnstileEnabled: "Enabled",
    turnstileDisabled: "Disabled",
    turnstileEnable: "Enable Verification",
    turnstileDisable: "Disable Verification",
    turnstileNotConfigured: "Turnstile environment variables are incomplete, so this feature cannot be enabled.",
    turnstileEnabledMessage: "Login verification enabled.",
    turnstileDisabledMessage: "Login verification disabled.",
    umamiTitle: "Umami Analytics",
    umamiDescription: "Connect self-hosted Umami or Umami Cloud to measure site visits. Save a complete configuration here before enabling or disabling analytics.",
    umamiScriptUrlLabel: "Analytics script URL",
    umamiScriptUrlPlaceholder: "https://example.com/script.js",
    umamiWebsiteIdLabel: "Website ID",
    umamiWebsiteIdPlaceholder: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    umamiEnabled: "Enabled",
    umamiDisabled: "Disabled",
    umamiEnable: "Enable Analytics",
    umamiDisable: "Disable Analytics",
    umamiSave: "Save Settings",
    umamiUpdated: "Umami settings saved.",
    umamiEnabledMessage: "Umami analytics enabled.",
    umamiDisabledMessage: "Umami analytics disabled.",
    umamiRequired: "Save the analytics script URL and Website ID before enabling analytics.",
    umamiInvalidUrl: "Enter a valid Umami analytics script URL.",
    proxyTitle: "Proxy Access",
    proxyDescription:
      "Proxy external images or links that cannot be reached directly, limited to the scope selected below; internal pages, APIs, and the site icon remain direct.\n\nCaution: enable this carefully. Some sites, image hotlink protection, or login redirects may be incompatible with the proxy. If the page displays incorrectly after enabling it, disable the proxy first or change proxy services.",
    proxyHelp:
      "Full-site proxy handles external links and images; Images only covers tool previews, article images, content-feed covers, and other image resources while regular external links remain direct. Direct prefix uses “proxy URL + target URL”; Edgeone-Proxy Standard uses `/proxy?url=`; Edgeone-Proxy Advanced uses `/advanced-proxy?url=`.\n\nHTools does not include a proxy service. Deploy a proxy project separately and enter its deployment URL if needed.",
    proxyEnabled: "Enabled",
    proxyDisabled: "Disabled",
    proxyUrlLabel: "Proxy service URL",
    proxyPlaceholder: "https://your-proxy.example.com/",
    proxyScopeLabel: "Proxy scope",
    proxyScopeAll: "Full-site proxy",
    proxyScopeImages: "Images only",
    proxyModeLabel: "Proxy access rule",
    proxyModePrefix: "Direct prefix",
    proxyModeEdgeOneProxy: "Edgeone-Proxy Standard",
    proxyModeEdgeOneAdvanced: "Edgeone-Proxy Advanced",
    proxyProjectLink: "Edgeone-Proxy Project",
    proxyEnable: "Enable Proxy",
    proxyDisable: "Disable Proxy",
    proxySave: "Save Settings",
    proxyRequired: "Enter a proxy service URL before enabling proxy fallback.",
    proxyInvalid: "Proxy service URL must be a valid http/https URL.",
    proxyUpdated: "Proxy settings updated.",
    resetTitle: "Restore Defaults",
    resetDescription:
      "Clear tools, articles, content flows, and saved categories, then disable the site source. Admin password and GitHub submission settings are kept.",
    resetWarning: "This will delete all imported data. Export a full backup first if needed.",
    resetButton: "Restore",
    resetConfirm:
      "Restore defaults? This will delete tools, articles, content flows, saved categories, and disable the site source.",
    resetDone: (result: FactoryResetResponse) =>
      `Restored defaults: deleted ${result.counts.tools} tools, ${result.counts.articles} articles, ${result.counts.contentSources} sources, and ${result.counts.contentItems} items.`,
    linkModuleTitle: "Site Link Check",
    linkModuleDescription:
      "Check whether stored project URLs and demo sites are reachable. Results are display-only and do not modify URLs.",
    urlLabel: "Project URL",
    demoUrlLabel: "Demo site"
  };
}

export function getAdminWorkspaceText(locale: Locale) {
  if (locale === "zh") {
    const scopeLabels: Record<AdminCategoryScope, string> = {
      tools: "\u5de5\u5177\u5e93",
      articles: "\u6587\u7ae0\u7ba1\u7406",
      content: "\u5185\u5bb9\u6d41"
    };

    return {
      articleLoadFailed: "\u65e0\u6cd5\u52a0\u8f7d\u6587\u7ae0\u3002",
      category: {
        topLabel: "\u65b0\u589e/\u7b5b\u9009\u5206\u7c7b",
        empty: "\u6ca1\u6709\u627e\u5230\u5206\u7c7b",
        createLabel: (category: string) => `\u65b0\u589e\u5206\u7c7b\uff1a${category}`,
        clearAllAction: "\u6e05\u7a7a\u5168\u90e8\u5185\u5bb9",
        deleteLabel: (label: string) => `\u5220\u9664\u5206\u7c7b\uff1a${label}`,
        moveLabel: (label: string) => `\u4e0a\u79fb\u5206\u7c7b\uff1a${label}`,
        scopeLabel: (scope: AdminCategoryScope) => scopeLabels[scope],
        loadFailed: "\u65e0\u6cd5\u52a0\u8f7d\u5206\u7c7b\u3002",
        updateFailed: "\u65e0\u6cd5\u66f4\u65b0\u5206\u7c7b\u3002",
        migrationTargetRequired: "\u8bf7\u9009\u62e9\u8981\u8fc1\u79fb\u5230\u7684\u5206\u7c7b\u3002",
        clearTitle: (scopeLabel: string) => `\u6e05\u7a7a${scopeLabel}`,
        manageTitle: (label: string) => `\u5904\u7406\u5206\u7c7b\u201c${label}\u201d`,
        deleteWithContentAction: "\u5220\u9664\u5206\u7c7b\u53ca\u5185\u5bb9",
        migrateAction: "\u8fc1\u79fb\u5185\u5bb9",
        clearDescription: (scopeLabel: string, count: number) =>
          `\u8fd9\u5c06\u6e05\u7a7a${scopeLabel}\u4e2d\u7684 ${count} \u6761\u5185\u5bb9\u3002`,
        occupiedDescription: (count: number) =>
          `\u8fd9\u4e2a\u5206\u7c7b\u4e0b\u8fd8\u6709 ${count} \u6761\u5185\u5bb9\u3002\u53ef\u4ee5\u8fc1\u79fb\u5230\u5176\u4ed6\u5206\u7c7b\uff0c\u4e5f\u53ef\u4ee5\u5220\u9664\u5206\u7c7b\u53ca\u5185\u5bb9\u3002`,
        migrateToLabel: "\u8fc1\u79fb\u5230\u5206\u7c7b",
        migrateHelp: "\u53ef\u9009\u62e9\u5df2\u6709\u5206\u7c7b\uff0c\u4e5f\u53ef\u4ee5\u8f93\u5165\u65b0\u5206\u7c7b\u3002",
        selectLabel: "\u9009\u62e9\u5206\u7c7b",
        cleared: (scopeLabel: string) => `${scopeLabel}\u5df2\u6e05\u7a7a\u5168\u90e8\u5185\u5bb9\u3002`,
        featuredCleared: "\u5de5\u5177\u5e93\u5df2\u53d6\u6d88\u6240\u6709\u7cbe\u9009\u5de5\u5177\u3002",
        removed: (label: string, scopeLabel: string) =>
          `\u5206\u7c7b\u201c${label}\u201d\u5df2\u4ece${scopeLabel}\u5220\u9664\u3002`,
        migrated: (label: string, targetLabel: string, affected: number) =>
          `\u5206\u7c7b\u201c${label}\u201d\u4e0b\u7684 ${affected} \u6761\u5185\u5bb9\u5df2\u8fc1\u79fb\u5230\u201c${targetLabel}\u201d\u3002`
      }
    };
  }

  const scopeLabels: Record<AdminCategoryScope, string> = {
    tools: "Tools",
    articles: "Articles",
    content: "Content Flow"
  };

  return {
    articleLoadFailed: "Unable to load article.",
    category: {
      topLabel: "Create / Filter Category",
      empty: "No matching categories",
      createLabel: (category: string) => `Create category: ${category}`,
      clearAllAction: "Clear all content",
      deleteLabel: (label: string) => `Delete category: ${label}`,
      moveLabel: (label: string) => `Move category up: ${label}`,
      scopeLabel: (scope: AdminCategoryScope) => scopeLabels[scope],
      loadFailed: "Unable to load categories.",
      updateFailed: "Unable to update category.",
      migrationTargetRequired: "Choose a category to migrate into.",
      clearTitle: (scopeLabel: string) => `Clear ${scopeLabel}`,
      manageTitle: (label: string) => `Manage category "${label}"`,
      deleteWithContentAction: "Delete category and content",
      migrateAction: "Migrate content",
      clearDescription: (scopeLabel: string, count: number) =>
        `This will clear ${count} items from ${scopeLabel}.`,
      occupiedDescription: (count: number) =>
        `This category still has ${count} items. You can migrate them to another category or delete the category and its content.`,
      migrateToLabel: "Migrate to category",
      migrateHelp: "Choose an existing category or type a new one.",
      selectLabel: "Select category",
      cleared: (scopeLabel: string) =>
        `${scopeLabel}: all content has been cleared.`,
      featuredCleared: "Tools: all featured tools have been unfeatured.",
      removed: (label: string, scopeLabel: string) =>
        `Category "${label}" removed from ${scopeLabel}.`,
      migrated: (label: string, targetLabel: string, affected: number) =>
        `${affected} items from "${label}" moved to "${targetLabel}".`
    }
  };
}

export function getContentFlowText(locale: Locale) {
  if (locale === "zh") {
    return {
      nav: "内容流",
      title: "内容流",
      description: "从 RSS 源同步外部内容，筛选后可转为站内文章。",
      addSource: "添加内容源",
      addContent: "添加内容",
      editSource: "编辑内容源",
      deleteSource: "删除内容源",
      syncSource: "同步",
      syncing: "同步中...",
      preview: "预览",
      saveSource: "保存内容源",
      sourceTitleLabel: "标题",
      sourceTitlePlaceholder: "留空则使用订阅源标题",
      sourceUrlLabel: "RSS / Atom 地址",
      sourceUrlPlaceholder: "https://blog.zrf.me/atom.xml",
      categoryLabel: "分类",
      categoryPlaceholder: "选择或新建分类",
      categoryEmptyLabel: "选择分类",
      categoryRequired: "请先选择内容源分类。",
      tagsLabel: "默认标签",
      tagsPlaceholder: "科技, 博客, 开源",
      enabledLabel: "启用内容源",
      enabledStatus: "已启用",
      disabledStatus: "已停用",
      enabledDraftEnabled: "内容源状态已改为启用，请点击保存内容源生效。",
      enabledDraftDisabled: "内容源状态已改为停用，请点击保存内容源生效。",
      searchPlaceholder: "搜索内容...",
      sourceEmptyTitle: "还没有内容源",
      sourceEmptyDescription: "添加 RSS / Atom 地址后，可以同步外部文章、视频或社交内容。",
      itemEmptyTitle: "还没有内容",
      itemEmptyDescription: "添加内容源并点击同步后，内容会显示在这里。",
      noMatchTitle: "没有匹配内容",
      noMatchDescription: "换个分类、来源或搜索词再试。",
      feedUrlNotAllowed: "该 RSS / Atom 地址不允许访问，请使用公开的 http/https 地址。",
      feedRedirectNotAllowed: "订阅源跳转到了不允许访问的地址。",
      feedTimeout: "订阅源请求超时，请稍后重试或更换地址。",
      feedTooLarge: "订阅源响应超过 5 MB，无法读取。",
      feedTooManyRedirects: "订阅源跳转次数过多，无法读取。",
      feedTypeUnsupported: "该地址返回的内容类型不是可识别的 RSS / Atom 文本。",
      feedEmpty: "订阅源返回了空内容。",
      feedNoItems: "订阅源中没有找到可同步的内容。",
      feedRequestFailed: (status: string) => `订阅源请求失败，状态码 ${status}。`,
      loadMore: "加载更多",
      previewTitle: "预览结果",
      previewLoaded: (count: number) => `预览已加载，共 ${count} 条内容。`,
      convert: "转为文章",
      converted: "已转文章",
      updateArticle: "更新文章",
      updateArticleAction: "更新文章",
      updateArticleTitle: "更新文章设置",
      updateArticleDescription:
        "只更新文章分类和发布状态，不会覆盖已经编辑过的标题、摘要和正文。",
      convertCategoryTitle: "选择文章分类",
      convertCategoryDescription:
        "请选择文章管理中的分类；也可以输入新分类，转换后会用于前台文章分流。",
      convertCategoryAction: "转为文章",
      convertCategoryRequired: "请先选择文章分类。",
      convertPublishLabel: "发布方式",
      convertAsDraft: "存为草稿",
      convertAsPublished: "直接发布",
      convertPublishDraftTip: "已切换为草稿，请确认。",
      convertPublishPublishedTip: "已切换为直接发布，请确认。",
      openOriginal: "打开原文",
      browseArticle: "本站浏览",
      saved: "内容源已保存。",
      savedSyncFailed: (message: string) => `内容源已保存，但首次同步失败：${message}`,
      deleted: "内容源已删除。",
      synced: (imported: number, updated: number) =>
        `同步完成：新增 ${imported} 条，刷新 ${updated} 条。`,
      convertedDone: "已转为文章并存为草稿，可在文章管理中继续编辑或发布。",
      convertedDraftDone: "已转为文章并存为草稿，可在文章管理中继续编辑或发布。",
      convertedPublishedDone: "已转为文章并直接发布，前台文章页可直接访问。",
      updatedDraftDone: "文章分类和发布状态已更新，当前保存为草稿。",
      updatedPublishedDone: "文章分类和发布状态已更新，当前已发布。",
      sourceUpdated: "来源有更新",
      reviewSourceUpdate: "查看更新",
      sourceUpdateTitle: "来源内容有更新",
      currentArticle: "当前文章",
      latestSource: "最新来源",
      ignoreSourceUpdate: "忽略此次更新",
      useLatestSource: "使用最新来源正文",
      sourceUpdateIgnored: "已忽略此次来源更新，当前文章保持不变。",
      sourceContentUpdated: "已使用最新来源正文，文章其他设置保持不变。",
      confirmSourceOverwrite: "确认覆盖文章正文？",
      confirmSourceOverwriteDescription:
        "只覆盖正文、原文链接和来源标记；不会修改标题、摘要、封面、标签、分类、Slug、发布状态和发布时间。",
      deleteConfirmTitle: "删除这个内容源吗？",
      deleteConfirmDescription: "删除后，此内容源下已同步的内容条目也会一起删除。",
      sourceCount: (count: number) => `${count} 条`
    };
  }

  return {
    nav: "Content Flow",
    title: "Content Flow",
    description:
      "Sync external RSS feeds, filter entries, and convert selected items into site articles.",
    addSource: "Add Source",
    addContent: "Add Content",
    editSource: "Edit Source",
    deleteSource: "Delete Source",
    syncSource: "Sync",
    syncing: "Syncing...",
    preview: "Preview",
    saveSource: "Save Source",
    sourceTitleLabel: "Title",
    sourceTitlePlaceholder: "Leave blank to use the feed title",
    sourceUrlLabel: "RSS / Atom URL",
    sourceUrlPlaceholder: "https://blog.zrf.me/atom.xml",
    categoryLabel: "Category",
    categoryPlaceholder: "Select or create a category",
    categoryEmptyLabel: "Select category",
    categoryRequired: "Select a content source category first.",
    tagsLabel: "Default tags",
    tagsPlaceholder: "Tech, Blog, Open Source",
    enabledLabel: "Enable source",
    enabledStatus: "Enabled",
    disabledStatus: "Disabled",
    enabledDraftEnabled: "Source status changed to enabled. Save the source to apply it.",
    enabledDraftDisabled: "Source status changed to disabled. Save the source to apply it.",
    searchPlaceholder: "Search content...",
    sourceEmptyTitle: "No content sources yet",
    sourceEmptyDescription:
      "Add RSS / Atom URLs to sync external articles, videos, or social content.",
    itemEmptyTitle: "No content yet",
    itemEmptyDescription: "Add a content source and sync it to show entries here.",
    noMatchTitle: "No matching content",
    noMatchDescription: "Try another category, source, or search term.",
    feedUrlNotAllowed: "This RSS / Atom URL is not allowed. Use a public http/https URL.",
    feedRedirectNotAllowed: "The feed redirected to a URL that is not allowed.",
    feedTimeout: "The feed request timed out. Try again later or use another URL.",
    feedTooLarge: "The feed response exceeds 5 MB and cannot be read.",
    feedTooManyRedirects: "The feed redirected too many times.",
    feedTypeUnsupported: "The URL did not return a supported RSS / Atom text type.",
    feedEmpty: "The feed returned an empty response.",
    feedNoItems: "No syncable items were found in the feed.",
    feedRequestFailed: (status: string) => `Feed request failed with status ${status}.`,
    loadMore: "Load more",
    previewTitle: "Preview",
    previewLoaded: (count: number) => `Preview loaded with ${count} items.`,
    convert: "Convert",
    converted: "Converted",
    updateArticle: "Update article",
    updateArticleAction: "Update article",
    updateArticleTitle: "Update article settings",
    updateArticleDescription:
      "Only the category and publish status will change. The edited title, summary, and content are preserved.",
    convertCategoryTitle: "Select article category",
    convertCategoryDescription:
      "Choose a category from article management, or create a new one for the public article filter.",
    convertCategoryAction: "Convert to article",
    convertCategoryRequired: "Select an article category first.",
    convertPublishLabel: "Publish mode",
    convertAsDraft: "Save draft",
    convertAsPublished: "Publish",
    convertPublishDraftTip:
      "Switched to draft. Confirm to apply.",
    convertPublishPublishedTip:
      "Switched to publish. Confirm to apply.",
    openOriginal: "Open Original",
    browseArticle: "View on site",
    saved: "Content source saved.",
    savedSyncFailed: (message: string) =>
      `Content source saved, but the initial sync failed: ${message}`,
    deleted: "Content source deleted.",
    synced: (imported: number, updated: number) =>
      `Sync complete: ${imported} imported, ${updated} refreshed.`,
    convertedDone:
      "Converted to an article draft. You can edit or publish it in article management.",
    convertedDraftDone:
      "Converted to an article draft. You can edit or publish it in article management.",
    convertedPublishedDone:
      "Converted and published. The public article page is now available.",
    updatedDraftDone: "The article category and status were updated as a draft.",
    updatedPublishedDone: "The article category and status were updated and published.",
    sourceUpdated: "Source updated",
    reviewSourceUpdate: "Review update",
    sourceUpdateTitle: "Source content updated",
    currentArticle: "Current article",
    latestSource: "Latest source",
    ignoreSourceUpdate: "Ignore this update",
    useLatestSource: "Use latest source content",
    sourceUpdateIgnored: "This source update was ignored and the article was unchanged.",
    sourceContentUpdated: "The latest source content was applied without changing other article settings.",
    confirmSourceOverwrite: "Replace article content?",
    confirmSourceOverwriteDescription:
      "Only the content, original link, and source marker will be replaced. Title, summary, cover, tags, category, slug, publish status, and dates remain unchanged.",
    deleteConfirmTitle: "Delete this content source?",
    deleteConfirmDescription:
      "Synced entries from this source will also be deleted.",
    sourceCount: (count: number) => `${count} items`
  };
}
